### ISSUE TITLE
Building a new ng-scope image doesn't work due to missing dependency

### ISSUE THREAD

**Issue by justus237** [j0lama/ng-scope-docker#5]
Hello,
I would like to build my own ng-scope image. However, this fails, because https://github.com/j0lama/libasn is not public.

Also just to note, the `ng-scope.sh` script has `start.sh` as the entry point, while all the pre-built images still have start.py (both `j0lama/ng-scope:latest` and `princetonpaws/ng-scope:22.04`). `ng-scope.sh` has docker commands for both scripts, but the `start.py` version is commented out. This effectively means the repo doesn't quite work as described in the readme out of the box.

Not sure whether anyone is working on this repo actively, but thought I'd open an issue anyway.

**Comment by j0lama** [comment]
Hello @justus237, 

I just fixed the compilation issue you were facing with libasn. libasn (now private) is an optional library used to decode SIB messages but it was treated as mandatory. I have fixed (now is not part of ng-scope-docker) that so now you should be able to compile your own image without any problems with the latest commit. If you want to use libasn, I encourage you to look at https://github.com/YaxiongXiePrinceton/NG-Scope/wiki/6.-ASN.1 where we explain how to compile libasn.
I have also built and pushed a newer version of j0lama/ng-scope:latest and removed all unnecessary scripts and files.

Let me know if you have any problems.

Jon
